export { default as loadingGrey } from './images/loadingGrey.gif'
export { default as logoImg } from './images/logo.svg'
export { default as loginBgImg } from './images/bg.svg'
export { default as loginImg } from './images/login-img.svg'
export { default as elar } from './images/alabuga.svg'
export { default as textLogoImg } from './images/text-logo.svg'
export { default as profileImage } from './images/profile-image@2x.png'
