export const GET_PENDING_DOCUMENTS_REQUEST = "GET_PENDING_DOCUMENTS_REQUEST";
export const GET_PENDING_DOCUMENTS_SUCCESS = "GET_PENDING_DOCUMENTS_SUCCESS";
export const GET_PENDING_DOCUMENTS_FAILURE = "GET_PENDING_DOCUMENTS_FAILURE";

export const GET_GLOBAL_SEARCH_REQUEST = "GET_GLOBAL_SEARCH_REQUEST";
export const GET_GLOBAL_SEARCH_SUCCESS = "GET_GLOBAL_SEARCH_SUCCESS";
export const GET_GLOBAL_SEARCH_FAILURE = "GET_GLOBAL_SEARCH_FAILURE";

export const SPLIT_PDF_REQUEST = 'SPLIT_PDF_REQUEST'
export const SPLIT_PDF_SUCCESS = 'SPLIT_PDF_SUCCESS'
export const SPLIT_PDF_FAILURE = 'SPLIT_PDF_FAILURE'

export const GET_JOURNAL_ENTRIES_REPORT_REQUEST =
  "GET_JOURNAL_ENTRIES_REPORT_REQUEST";
export const GET_JOURNAL_ENTRIES_REPORT_SUCCESS =
  "GET_JOURNAL_ENTRIES_REPORT_SUCCESS";
export const GET_JOURNAL_ENTRIES_REPORT_FAILURE =
  "GET_JOURNAL_ENTRIES_REPORT_FAILURE";

export const GET_GENERAL_LEDGER_REPORT_REQUEST =
  "GET_GENERAL_LEDGER_REPORT_REQUEST";
export const GET_GENERAL_LEDGER_REPORT_SUCCESS =
  "GET_GENERAL_LEDGER_REPORT_SUCCESS";
export const GET_GENERAL_LEDGER_REPORT_FAILURE =
  "GET_GENERAL_LEDGER_REPORT_FAILURE";

export const GET_VAT_REPORT_REQUEST = "GET_VAT_REPORT_REQUEST";
export const GET_VAT_REPORT_SUCCESS = "GET_VAT_REPORT_SUCCESS";
export const GET_VAT_REPORT_FAILURE = "GET_VAT_REPORT_FAILURE";

export const GET_INCOME_STATEMENT_REPORT_REQUEST =
  "GET_INCOME_STATEMENT_REPORT_REQUEST";
export const GET_INCOME_STATEMENT_REPORT_SUCCESS =
  "GET_INCOME_STATEMENT_REPORT_SUCCESS";
export const GET_INCOME_STATEMENT_REPORT_FAILURE =
  "GET_INCOME_STATEMENT_REPORT_FAILURE";

export const GET_TRIAL_BALANCE_REPORT_REQUEST =
  "GET_TRIAL_BALANCE_REPORT_REQUEST";
export const GET_TRIAL_BALANCE_REPORT_SUCCESS =
  "GET_TRIAL_BALANCE_REPORT_SUCCESS";
export const GET_TRIAL_BALANCE_REPORT_FAILURE =
  "GET_TRIAL_BALANCE_REPORT_FAILURE";

export const GET_ACCOUNT_RECEIVABLE_REPORT_REQUEST =
  "GET_ACCOUNT_RECEIVABLE_REPORT_REQUEST";
export const GET_ACCOUNT_RECEIVABLE_REPORT_SUCCESS =
  "GET_ACCOUNT_RECEIVABLE_REPORT_SUCCESS";
export const GET_ACCOUNT_RECEIVABLE_REPORT_FAILURE =
  "GET_ACCOUNT_RECEIVABLE_REPORT_FAILURE";

export const GET_ACCOUNT_PAYABLE_REPORT_REQUEST =
  "GET_ACCOUNT_PAYABLE_REPORT_REQUEST";
export const GET_ACCOUNT_PAYABLE_REPORT_SUCCESS =
  "GET_ACCOUNT_PAYABLE_REPORT_SUCCESS";
export const GET_ACCOUNT_PAYABLE_REPORT_FAILURE =
  "GET_ACCOUNT_PAYABLE_REPORT_FAILURE";

export const GET_BALANCE_SHEET_REPORT_REQUEST =
  "GET_BALANCE_SHEET_REPORT_REQUEST";
export const GET_BALANCE_SHEET_REPORT_SUCCESS =
  "GET_BALANCE_SHEET_REPORT_SUCCESS";
export const GET_BALANCE_SHEET_REPORT_FAILURE =
  "GET_BALANCE_SHEET_REPORT_FAILURE";

export const RESET_BANK_TRANSACTIONS = "RESET_BANK_TRANSACTIONS";
export const GET_BANK_TRANSACTIONS_REQUEST = "GET_BANK_TRANSACTIONS_REQUEST";
export const GET_BANK_TRANSACTIONS_SUCCESS = "GET_BANK_TRANSACTIONS_SUCCESS";
export const GET_BANK_TRANSACTIONS_FAILURE = "GET_BANK_TRANSACTIONS_FAILURE";

export const GET_DOCUMENT_SUGGESTIONS_REQUEST =
  "GET_DOCUMENT_SUGGESTIONS_REQUEST";
export const GET_DOCUMENT_SUGGESTIONS_SUCCESS =
  "GET_DOCUMENT_SUGGESTIONS_SUCCESS";
export const GET_DOCUMENT_SUGGESTIONS_FAILURE =
  "GET_DOCUMENT_SUGGESTIONS_FAILURE";

export const CREATE_PAYMENT_REQUEST = "CREATE_PAYMENT_REQUEST";
export const CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS";
export const CREATE_PAYMENT_FAILURE = "CREATE_PAYMENT_FAILURE";

export const CREATE_PAYMENT_REQUEST_REQUEST = "CREATE_PAYMENT_REQUEST_REQUEST";
export const CREATE_PAYMENT_REQUEST_SUCCESS = "CREATE_PAYMENT_REQUEST_SUCCESS";
export const CREATE_PAYMENT_REQUEST_FAILURE = "CREATE_PAYMENT_REQUEST_FAILURE";

export const GET_ACCOUNT_BALANCES_REQUEST = "GET_ACCOUNT_BALANCES_REQUEST";
export const GET_ACCOUNT_BALANCES_SUCCESS = "GET_ACCOUNT_BALANCES_SUCCESS";
export const GET_ACCOUNT_BALANCES_FAILURE = "GET_ACCOUNT_BALANCES_FAILURE";

export const GET_JOURNAL_ENTRIES_REQUEST = "GET_JOURNAL_ENTRIES_REQUEST";
export const GET_JOURNAL_ENTRIES_SUCCESS = "GET_JOURNAL_ENTRIES_SUCCESS";
export const GET_JOURNAL_ENTRIES_FAILURE = "GET_JOURNAL_ENTRIES_FAILURE";

export const CREATE_JOURNAL_ENTRY_REQUEST = "CREATE_JOURNAL_ENTRY_REQUEST";
export const CREATE_JOURNAL_ENTRY_SUCCESS = "CREATE_JOURNAL_ENTRY_SUCCESS";
export const CREATE_JOURNAL_ENTRY_FAILURE = "CREATE_JOURNAL_ENTRY_FAILURE";

export const GET_JOURNAL_ENTRY_LINES_REQUEST =
  "GET_JOURNAL_ENTRY_LINES_REQUEST";
export const GET_JOURNAL_ENTRY_LINES_SUCCESS =
  "GET_JOURNAL_ENTRY_LINES_SUCCESS";
export const GET_JOURNAL_ENTRY_LINES_FAILURE =
  "GET_JOURNAL_ENTRY_LINES_FAILURE";

export const GET_RECONCILIATIONS_REQUEST = "GET_RECONCILIATIONS_REQUEST";
export const GET_RECONCILIATIONS_SUCCESS = "GET_RECONCILIATIONS_SUCCESS";
export const GET_RECONCILIATIONS_FAILURE = "GET_RECONCILIATIONS_FAILURE";

export const CREATE_RECONCILIATION_REQUEST = "CREATE_RECONCILIATION_REQUEST";
export const CREATE_RECONCILIATION_SUCCESS = "CREATE_RECONCILIATION_SUCCESS";
export const CREATE_RECONCILIATION_FAILURE = "CREATE_RECONCILIATION_FAILURE";

export const SET_SELECTION_BANK_ACCOUNT = "SET_SELECTION_BANK_ACCOUNT";
