
export const GET_CLIENT_ACCOUNTS_REQUEST = 'GET_CLIENT_ACCOUNTS_REQUEST'
export const GET_CLIENT_ACCOUNTS_SUCCESS = 'GET_CLIENT_ACCOUNTS_SUCCESS'
export const GET_CLIENT_ACCOUNTS_FAILURE = 'GET_CLIENT_ACCOUNTS_FAILURE'

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE'

export const GET_USERS_STATISTIC_REQUEST = 'GET_USERS_STATISTIC_REQUEST'
export const GET_USERS_STATISTIC_SUCCESS = 'GET_USERS_STATISTIC_SUCCESS'
export const GET_USERS_STATISTIC_FAILURE = 'GET_USERS_STATISTIC_FAILURE'

export const GET_CONTRACTS_REQUEST = 'GET_CONTRACTS_REQUEST'
export const GET_CONTRACTS_SUCCESS = 'GET_CONTRACTS_SUCCESS'
export const GET_CONTRACTS_FAILURE = 'GET_CONTRACTS_FAILURE'

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE'

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE'

export const CREATE_CONTRACT_REQUEST = 'CREATE_CONTRACT_REQUEST'
export const CREATE_CONTRACT_SUCCESS = 'CREATE_CONTRACT_SUCCESS'
export const CREATE_CONTRACT_FAILURE = 'CREATE_CONTRACT_FAILURE'

export const EDIT_CONTRACT_REQUEST = 'EDIT_CONTRACT_REQUEST'
export const EDIT_CONTRACT_SUCCESS = 'EDIT_CONTRACT_SUCCESS'
export const EDIT_CONTRACT_FAILURE = 'EDIT_CONTRACT_FAILURE'

export const CREATE_CLIENT_COMPANY_REQUEST = 'CREATE_CLIENT_COMPANY_REQUEST'
export const CREATE_CLIENT_COMPANY_SUCCESS = 'CREATE_CLIENT_COMPANY_SUCCESS'
export const CREATE_CLIENT_COMPANY_FAILURE = 'CREATE_CLIENT_COMPANY_FAILURE'

export const EDIT_CLIENT_COMPANY_REQUEST = 'EDIT_CLIENT_COMPANY_REQUEST'
export const EDIT_CLIENT_COMPANY_SUCCESS = 'EDIT_CLIENT_COMPANY_SUCCESS'
export const EDIT_CLIENT_COMPANY_FAILURE = 'EDIT_CLIENT_COMPANY_FAILURE'

export const CREATE_CLIENT_USER_RELATIONSHIP_REQUEST = 'CREATE_CLIENT_USER_RELATIONSHIP__REQUEST'
export const CREATE_CLIENT_USER_RELATIONSHIP_SUCCESS = 'CREATE_CLIENT_USER_RELATIONSHIP__SUCCESS'
export const CREATE_CLIENT_USER_RELATIONSHIP_FAILURE = 'CREATE_CLIENT_USER_RELATIONSHIP__FAILURE'

export const EDIT_CLIENT_USER_RELATIONSHIP_REQUEST = 'EDIT_CLIENT_USER_RELATIONSHIP__REQUEST'
export const EDIT_CLIENT_USER_RELATIONSHIP_SUCCESS = 'EDIT_CLIENT_USER_RELATIONSHIP__SUCCESS'
export const EDIT_CLIENT_USER_RELATIONSHIP_FAILURE = 'EDIT_CLIENT_USER_RELATIONSHIP__FAILURE'

export const DELETE_CLIENT_USER_RELATIONSHIP_REQUEST = 'DELETE_CLIENT_USER_RELATIONSHIP__REQUEST'
export const DELETE_CLIENT_USER_RELATIONSHIP_SUCCESS = 'DELETE_CLIENT_USER_RELATIONSHIP__SUCCESS'
export const DELETE_CLIENT_USER_RELATIONSHIP_FAILURE = 'DELETE_CLIENT_USER_RELATIONSHIP__FAILURE'

export const DELETE_CLIENT_COMPANY_REQUEST = 'DELETE_CLIENT_COMPANY_REQUEST'
export const DELETE_CLIENT_COMPANY_SUCCESS = 'DELETE_CLIENT_COMPANY_SUCCESS'
export const DELETE_CLIENT_COMPANY_FAILURE = 'DELETE_CLIENT_COMPANY_FAILURE'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE'

export const DELETE_CONTRACT_REQUEST = 'DELETE_CONTRACT_REQUEST'
export const DELETE_CONTRACT_SUCCESS = 'DELETE_CONTRACT_SUCCESS'
export const DELETE_CONTRACT_FAILURE = 'DELETE_CONTRACT_FAILURE'
