export const SET_HEADER_TEXT = 'SET_HEADER_TEXT'
export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'
export const CHANGE_LOCATE_SUCCESS = 'CHANGE_LOCATE_SUCCESS'

export const SET_CURRENT_ACCOUNT = 'SET_CURRENT_ACCOUNT'
export const SET_CURRENT_CONTRACT = 'SET_CURRENT_CONTRACT'

export const SET_USER = 'SET_USER'
