export const GET_CHAT_CHANNELS_REQUEST = 'GET_CHAT_CHANNELS_REQUEST'
export const GET_CHAT_CHANNELS_SUCCESS = 'GET_CHAT_CHANNELS_SUCCESS'
export const GET_ALL_CHAT_CHANNELS_SUCCESS = 'GET_ALL_CHAT_CHANNELS_SUCCESS'
export const GET_CHAT_CHANNELS_FAILURE = 'GET_CHAT_CHANNELS_FAILURE'

export const GET_CHAT_MESSAGES_REQUEST = 'GET_CHAT_MESSAGES_REQUEST'
export const GET_CHAT_MESSAGES_SUCCESS = 'GET_CHAT_MESSAGES_SUCCESS'
export const GET_CHAT_MESSAGES_FAILURE = 'GET_CHAT_MESSAGES_FAILURE'
export const CLEAR_CHAT_MESSAGES = 'CLEAR_CHAT_MESSAGES'

export const CREATE_CHAT_MESSAGE_REQUEST = 'CREATE_CHAT_MESSAGE_REQUEST'
export const CREATE_CHAT_MESSAGE_SUCCESS = 'CREATE_CHAT_MESSAGE_SUCCESS'
export const CREATE_CHAT_MESSAGE_FAILURE = 'CREATE_CHAT_MESSAGE_FAILURE'

export const READ_CHAT_MESSAGE_REQUEST = 'READ_CHAT_MESSAGE_REQUEST'
export const READ_CHAT_MESSAGE_SUCCESS = 'READ_CHAT_MESSAGE_SUCCESS'
export const READ_CHAT_MESSAGE_FAILURE = 'READ_CHAT_MESSAGE_FAILURE'

export const GET_CHAT_USERS_REQUEST = 'GET_CHAT_USERS_REQUEST'
export const GET_CHAT_USERS_SUCCESS = 'GET_CHAT_USERS_SUCCESS'
export const GET_CHAT_USERS_FAILURE = 'GET_CHAT_USERS_FAILURE'

export const ADD_CHAT_USER_REQUEST = 'ADD_CHAT_USER_REQUEST'
export const ADD_CHAT_USER_SUCCESS = 'ADD_CHAT_USER_SUCCESS'
export const ADD_CHAT_USER_FAILURE = 'ADD_CHAT_USER_FAILURE'

export const DELETE_CHAT_USER_REQUEST = 'DELETE_CHAT_USER_REQUEST'
export const DELETE_CHAT_USER_SUCCESS = 'DELETE_CHAT_USER_SUCCESS'
export const DELETE_CHAT_USER_FAILURE = 'DELETE_CHAT_USER_FAILURE'

export const CREATE_CHAT_CHANNEL_REQUEST = 'CREATE_CHAT_CHANNEL_REQUEST'
export const CREATE_CHAT_CHANNEL_SUCCESS = 'CREATE_CHAT_CHANNEL_SUCCESS'
export const CREATE_CHAT_CHANNEL_FAILURE = 'CREATE_CHAT_CHANNEL_FAILURE'

export const DELETE_CHAT_CHANNEL_REQUEST = 'DELETE_CHAT_CHANNEL_REQUEST'
export const DELETE_CHAT_CHANNEL_SUCCESS = 'DELETE_CHAT_CHANNEL_SUCCESS'
export const DELETE_CHAT_CHANNEL_FAILURE = 'DELETE_CHAT_CHANNEL_FAILURE'
