export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

export const SUBMIT_NEW_PASSWORD_REQUEST = "SUBMIT_NEW_PASSWORD_REQUEST";
export const SUBMIT_NEW_PASSWORD_SUCCESS = "SUBMIT_NEW_PASSWORD_SUCCESS";
export const SUBMIT_NEW_PASSWORD_FAILURE = "SUBMIT_NEW_PASSWORD_FAILURE";

export const UPLOAD_DOCUMENTS_REQUEST = "UPLOAD_DOCUMENTS_REQUEST";
export const UPLOAD_DOCUMENTS_SUCCESS = "UPLOAD_DOCUMENTS_SUCCESS";
export const UPLOAD_DOCUMENTS_FAILURE = "UPLOAD_DOCUMENTS_FAILURE";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const GET_OVERVIEW_REQUEST = "GET_OVERVIEW_REQUEST";
export const GET_OVERVIEW_SUCCESS = "GET_OVERVIEW_SUCCESS";
export const GET_OVERVIEW_FAILURE = "GET_OVERVIEW_FAILURE";

export const GET_CURRENCY_REQUEST = "GET_CURRENCY_REQUEST";
export const GET_CURRENCY_SUCCESS = "GET_CURRENCY_SUCCESS";
export const GET_CURRENCY_FAILURE = "GET_CURRENCY_FAILURE";

export const GET_DOCUMENTS_REQUEST = "GET_DOCUMENTS_REQUEST";
export const GET_DOCUMENTS_SUCCESS = "GET_DOCUMENTS_SUCCESS";
export const GET_DOCUMENTS_FAILURE = "GET_DOCUMENTS_FAILURE";

export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE";

export const GET_POST_DETAIL_REQUEST = "GET_POST_DETAIL_REQUEST";
export const GET_POST_DETAIL_SUCCESS = "GET_POST_DETAIL_SUCCESS";
export const GET_POST_DETAIL_FAILURE = "GET_POST_DETAIL_FAILURE";

export const GET_VOUCHERS_REQUEST = "GET_VOUCHERS_REQUEST";
export const GET_VOUCHERS_SUCCESS = "GET_VOUCHERS_SUCCESS";
export const GET_VOUCHERS_FAILURE = "GET_VOUCHERS_FAILURE";

export const GET_VOUCHER_REQUEST = "GET_VOUCHER_REQUEST";
export const GET_VOUCHER_SUCCESS = "GET_VOUCHER_SUCCESS";
export const GET_VOUCHER_FAILURE = "GET_VOUCHER_FAILURE";

export const GET_VOUCHER_CATEGORIES_REQUEST = "GET_VOUCHER_CATEGORIES_REQUEST";
export const GET_VOUCHER_CATEGORIES_SUCCESS = "GET_VOUCHER_CATEGORIES_SUCCESS";
export const GET_VOUCHER_CATEGORIES_FAILURE = "GET_VOUCHER_CATEGORIES_FAILURE";

export const GET_KLIPPA_DATA_REQUEST = "GET_KLIPPA_DATA_REQUEST";
export const GET_KLIPPA_DATA_SUCCESS = "GET_KLIPPA_DATA_SUCCESS";
export const GET_KLIPPA_DATA_FAILURE = "GET_KLIPPA_DATA_FAILURE";

export const GET_QUESTION_TEMPLATES_REQUEST = "GET_QUESTION_TEMPLATES_REQUEST";
export const GET_QUESTION_TEMPLATES_SUCCESS = "GET_QUESTION_TEMPLATES_SUCCESS";
export const GET_QUESTION_TEMPLATES_FAILURE = "GET_QUESTION_TEMPLATES_FAILURE";

export const CREATE_QUESTION_TEMPLATES_REQUEST =
  "CREATE_QUESTION_TEMPLATES_REQUEST";
export const CREATE_QUESTION_TEMPLATES_SUCCESS =
  "CREATE_QUESTION_TEMPLATES_SUCCESS";
export const CREATE_QUESTION_TEMPLATES_FAILURE =
  "CREATE_QUESTION_TEMPLATES_FAILURE";

export const UPDATE_QUESTION_TEMPLATES_REQUEST =
  "UPDATE_QUESTION_TEMPLATES_REQUEST";
export const UPDATE_QUESTION_TEMPLATES_SUCCESS =
  "UPDATE_QUESTION_TEMPLATES_SUCCESS";
export const UPDATE_QUESTION_TEMPLATES_FAILURE =
  "UPDATE_QUESTION_TEMPLATES_FAILURE";

export const DELETE_QUESTION_TEMPLATES_REQUEST =
  "DELETE_QUESTION_TEMPLATES_REQUEST";
export const DELETE_QUESTION_TEMPLATES_SUCCESS =
  "DELETE_QUESTION_TEMPLATES_SUCCESS";
export const DELETE_QUESTION_TEMPLATES_FAILURE =
  "DELETE_QUESTION_TEMPLATES_FAILURE";

export const CREATE_ACCOUNTING_QUESTIONS_REQUEST =
  "CREATE_ACCOUNTING_QUESTIONS_REQUEST";
export const CREATE_ACCOUNTING_QUESTIONS_SUCCESS =
  "CREATE_ACCOUNTING_QUESTIONS_SUCCESS";
export const CREATE_ACCOUNTING_QUESTIONS_FAILURE =
  "CREATE_ACCOUNTING_QUESTIONS_FAILURE";

export const GET_ACCOUNTING_QUESTIONS_REQUEST =
  "GET_ACCOUNTING_QUESTIONS_REQUEST";
export const GET_ACCOUNTING_QUESTIONS_SUCCESS =
  "GET_ACCOUNTING_QUESTIONS_SUCCESS";
export const GET_ACCOUNTING_QUESTIONS_FAILURE =
  "GET_ACCOUNTING_QUESTIONS_FAILURE";

export const GET_ACCOUNTING_QUESTIONS_IN_DOCUMENT_DETAIL_REQUEST =
  "GET_ACCOUNTING_QUESTIONS_IN_DOCUMENT_DETAIL_REQUEST";
export const GET_ACCOUNTING_QUESTIONS_IN_DOCUMENT_DETAIL_SUCCESS =
  "GET_ACCOUNTING_QUESTIONS_IN_DOCUMENT_DETAIL_SUCCESS";
export const GET_ACCOUNTING_QUESTIONS_IN_DOCUMENT_DETAIL_FAILURE =
  "GET_ACCOUNTING_QUESTIONS_IN_DOCUMENT_DETAIL_FAILURE";

export const ANSWER_ACCOUNTING_QUESTION_REQUEST =
  "ANSWER_ACCOUNTING_QUESTION_REQUEST";
export const ANSWER_ACCOUNTING_QUESTION_SUCCESS =
  "ANSWER_ACCOUNTING_QUESTION_SUCCESS";
export const ANSWER_ACCOUNTING_QUESTION_FAILURE =
  "ANSWER_ACCOUNTING_QUESTION_FAILURE";

export const CREATE_BUSINESS_PARTNERS_REQUEST =
  "CREATE_BUSINESS_PARTNERS_REQUEST";
export const CREATE_BUSINESS_PARTNERS_SUCCESS =
  "CREATE_BUSINESS_PARTNERS_SUCCESS";
export const CREATE_BUSINESS_PARTNERS_FAILURE =
  "CREATE_BUSINESS_PARTNERS_FAILURE";

export const UPDATE_BUSINESS_PARTNER_REQUEST =
  "UPDATE_BUSINESS_PARTNER_REQUEST";
export const UPDATE_BUSINESS_PARTNER_SUCCESS =
  "UPDATE_BUSINESS_PARTNER_SUCCESS";
export const UPDATE_BUSINESS_PARTNER_FAILURE =
  "UPDATE_BUSINESS_PARTNER_FAILURE";

export const CREATE_PROJECTS_REQUEST = "CREATE_PROJECTS_REQUEST";
export const CREATE_PROJECTS_SUCCESS = "CREATE_PROJECTS_SUCCESS";
export const CREATE_PROJECTS_FAILURE = "CREATE_PROJECTS_FAILURE";

export const UPDATE_PROJECT_REQUEST = "UPDATE_PROJECT_REQUEST";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAILURE = "UPDATE_PROJECT_FAILURE";

export const CREATE_ASSETS_REQUEST = "CREATE_ASSETS_REQUEST";
export const CREATE_ASSETS_SUCCESS = "CREATE_ASSETS_SUCCESS";
export const CREATE_ASSETS_FAILURE = "CREATE_ASSETS_FAILURE";

export const UPDATE_ASSET_REQUEST = "UPDATE_ASSET_REQUEST";
export const UPDATE_ASSET_SUCCESS = "UPDATE_ASSET_SUCCESS";
export const UPDATE_ASSET_FAILURE = "UPDATE_ASSET_FAILURE";

export const GET_ORGANIZATIONS_REQUEST = "GET_ORGANIZATIONS_REQUEST";
export const GET_ORGANIZATIONS_SUCCESS = "GET_ORGANIZATIONS_SUCCESS";
export const GET_ORGANIZATIONS_FAILURE = "GET_ORGANIZATIONS_FAILURE";

export const GET_BUSINESS_PARTNERS_REQUEST = "GET_BUSINESS_PARTNERS_REQUEST";
export const GET_BUSINESS_PARTNERS_SUCCESS = "GET_BUSINESS_PARTNERS_SUCCESS";
export const GET_BUSINESS_PARTNERS_FAILURE = "GET_BUSINESS_PARTNERS_FAILURE";

export const GET_BANK_ACCOUNTS_REQUEST = "GET_BANK_ACCOUNTS_REQUEST";
export const GET_BANK_ACCOUNTS_SUCCESS = "GET_BANK_ACCOUNTS_SUCCESS";
export const GET_BANK_ACCOUNTS_FAILURE = "GET_BANK_ACCOUNTS_FAILURE";

export const GET_PROJECTS_REQUEST = "GET_PROJECTS_REQUEST";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAILURE = "GET_PROJECTS_FAILURE";

export const GET_ASSETS_REQUEST = "GET_ASSETS_REQUEST";
export const GET_ASSETS_SUCCESS = "GET_ASSETS_SUCCESS";
export const GET_ASSETS_FAILURE = "GET_ASSETS_FAILURE";

export const GET_IBAN_CALCULATION_REQUEST = "GET_IBAN_CALCULATION_REQUEST";
export const GET_IBAN_CALCULATION_SUCCESS = "GET_IBAN_CALCULATION_SUCCESS";
export const GET_IBAN_CALCULATION_FAILURE = "GET_IBAN_CALCULATION_FAILURE";

export const GET_IBAN_VALIDATION_REQUEST = "GET_IBAN_VALIDATION_REQUEST";
export const GET_IBAN_VALIDATION_SUCCESS = "GET_IBAN_VALIDATION_SUCCESS";
export const GET_IBAN_VALIDATION_FAILURE = "GET_IBAN_VALIDATION_FAILURE";

export const CREATE_BANK_ACCOUNTS_REQUEST = "CREATE_BANK_ACCOUNTS_REQUEST";
export const CREATE_BANK_ACCOUNTS_SUCCESS = "CREATE_BANK_ACCOUNTS_SUCCESS";
export const CREATE_BANK_ACCOUNTS_FAILURE = "CREATE_BANK_ACCOUNTS_FAILURE";

export const CREATE_POST_ARCHIVE_REQUEST = "CREATE_POST_ARCHIVE_REQUEST";
export const CREATE_POST_ARCHIVE_SUCCESS = "CREATE_POST_ARCHIVE_SUCCESS";
export const CREATE_POST_ARCHIVE_FAILURE = "CREATE_POST_ARCHIVE_FAILURE";

export const CREATE_POST_REVERSE_REQUEST = "CREATE_POST_REVERSE_REQUEST";
export const CREATE_POST_REVERSE_SUCCESS = "CREATE_POST_REVERSE_SUCCESS";
export const CREATE_POST_REVERSE_FAILURE = "CREATE_POST_REVERSE_FAILURE";

export const CREATE_POSTS_REQUEST = "CREATE_POSTS_REQUEST";
export const CREATE_POSTS_SUCCESS = "CREATE_POSTS_SUCCESS";
export const CREATE_POSTS_FAILURE = "CREATE_POSTS_FAILURE";

export const DELETE_POSTS_REQUEST = "DELETE_POSTS_REQUEST";
export const DELETE_POSTS_SUCCESS = "DELETE_POSTS_SUCCESS";
export const DELETE_POSTS_FAILURE = "DELETE_POSTS_FAILURE";

export const GET_ACCOUNTING_ACCOUNTS_REQUEST =
  "GET_ACCOUNTING_ACCOUNTS_REQUEST";
export const GET_ACCOUNTING_ACCOUNTS_SUCCESS =
  "GET_ACCOUNTING_ACCOUNTS_SUCCESS";
export const GET_ACCOUNTING_ACCOUNTS_FAILURE =
  "GET_ACCOUNTING_ACCOUNTS_FAILURE";

export const GET_JOURNAL_ENTRIES_RAW_REQUEST =
  "GET_JOURNAL_ENTRIES_RAW_REQUEST";
export const GET_JOURNAL_ENTRIES_RAW_SUCCESS =
  "GET_JOURNAL_ENTRIES_RAW_SUCCESS";
export const GET_JOURNAL_ENTRIES_RAW_FAILURE =
  "GET_JOURNAL_ENTRIES_RAW_FAILURE";

export const GET_TAX_CODES_REQUEST = "GET_TAX_CODES_REQUEST";
export const GET_TAX_CODES_SUCCESS = "GET_TAX_CODES_SUCCESS";
export const GET_TAX_CODES_FAILURE = "GET_TAX_CODES_FAILURE";

export const COUNT_PENDING_DOCUMENTS_REQUEST =
  "COUNT_PENDING_DOCUMENTS_REQUEST";
export const COUNT_PENDING_DOCUMENTS_SUCCESS =
  "COUNT_PENDING_DOCUMENTS_SUCCESS";
export const COUNT_PENDING_DOCUMENTS_FAILURE =
  "COUNT_PENDING_DOCUMENTS_FAILURE";

export const GET_ORGANIZATION_REQUEST = "GET_ORGANIZATION_REQUEST";
export const GET_ORGANIZATION_SUCCESS = "GET_ORGANIZATION_SUCCESS";
export const GET_ORGANIZATION_FAILURE = "GET_ORGANIZATION_FAILURE";

export const GET_LABELS_REQUEST = "GET_LABELS_REQUEST";
export const GET_LABELS_SUCCESS = "GET_LABELS_SUCCESS";
export const GET_LABELS_FAILURE = "GET_LABELS_FAILURE";

export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";

export const CREATE_DOC_REQUEST = "CREATE_DOC_REQUEST";
export const CREATE_DOC_SUCCESS = "CREATE_DOC_SUCCESS";
export const CREATE_DOC_FAILURE = "CREATE_DOC_FAILURE";

export const CREATE_EXPERIMENT_REQUEST = "CREATE_EXPERIMENT_REQUEST";
export const CREATE_EXPERIMENT_SUCCESS = "CREATE_EXPERIMENT_SUCCESS";
export const CREATE_EXPERIMENT_FAILURE = "CREATE_EXPERIMENT_FAILURE";

export const GET_UNITS_REQUEST = "GET_UNITS_REQUEST";
export const GET_UNITS_SUCCESS = "GET_UNITS_SUCCESS";
export const GET_UNITS_FAILURE = "GET_UNITS_FAILURE";

export const GET_ITEMS_REQUEST = "GET_ITEMS_REQUEST";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAILURE = "GET_ITEMS_FAILURE";

export const ADD_ITEM_REQUEST = "ADD_ITEM_REQUEST";
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";
export const ADD_ITEM_FAILURE = "ADD_ITEM_FAILURE";

export const GET_CATEGORIES_LV1_REQUEST = "GET_CATEGORIES_LV1_REQUEST";
export const GET_CATEGORIES_LV1_SUCCESS = "GET_CATEGORIES_LV1_SUCCESS";
export const GET_CATEGORIES_LV1_FAILURE = "GET_CATEGORIES_LV1_FAILURE";
