export const GET_EXCHANGE_RATES_REQUEST = 'GET_EXCHANGE_RATES_REQUEST'
export const GET_EXCHANGE_RATES_SUCCESS = 'GET_EXCHANGE_RATES_SUCCESS'
export const GET_EXCHANGE_RATES_FAILURE = 'GET_EXCHANGE_RATES_FAILURE'
